#!/bin/sh

set -ex

TEST_REALM="EXAMPLE.INTERNAL"

# start fresh
rm -rf /var/lib/krb5kdc/*
rm -rf /etc/krb5kdc/*

# setup some defaults
cat > /etc/krb5kdc/kdc.conf <<EOF
[kdcdefaults]
    kdc_ports = 750,88
[realms]
    ${TEST_REALM} = {
	    database_name = /var/lib/krb5kdc/principal
	    admin_keytab = FILE:/etc/krb5kdc/kadm5.keytab
	    acl_file = /etc/krb5kdc/kadm5.acl
	    key_stash_file = /etc/krb5kdc/stash
	    kdc_ports = 750,88
	    max_life = 10h 0m 0s
	    max_renewable_life = 7d 0h 0m 0s
	    master_key_type = des3-hmac-sha1
	    #supported_enctypes = aes256-cts:normal aes128-cts:normal
	    default_principal_flags = +preauth
    }
EOF

cat > /etc/krb5.conf <<EOF
[libdefaults]
    default_realm = ${TEST_REALM}
    kdc_timesync = 1
    ccache_type = 4
    forwardable = true
    proxiable = true
    fcc-mit-ticketflags = true
[realms]
	EXAMPLE.INTERNAL = {
		kdc = localhost
		admin_server = localhost
	}
EOF
cat > /etc/krb5kdc/kadm5.acl <<EOF
# */admin *
EOF

# create the realm
kdb5_util create -s -P secretpassword

# restart services
systemctl restart krb5-kdc.service krb5-admin-server.service

# create a random-enough principal
principal="testuser$$"
kadmin.local -q "addprinc -pw secret ${principal}"

# get a ticket
echo secret | kinit ${principal}

# did we really get a ticket?
klist | grep krbtgt/EXAMPLE.INTERNAL@EXAMPLE.INTERNAL

# destroy it
kdestroy

# delete the principal
kadmin.local -q "delprinc -force ${principal}"
